/**
 * @file arm.c
 *
 * @brief This source file was generated by cantools version 44.1.0 Thu Sep 17 23:02:21 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "arm.h"

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int arm_joint1_pack(
    uint8_t *dst_p,
    const struct arm_joint1_t *src_p,
    size_t size)
{
    uint32_t joint1_pos;
    uint32_t joint1_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint1_vel, &src_p->joint1_vel, sizeof(joint1_vel));
    dst_p[0] |= pack_left_shift_u32(joint1_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint1_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint1_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint1_vel, 24u, 0xffu);
    memcpy(&joint1_pos, &src_p->joint1_pos, sizeof(joint1_pos));
    dst_p[4] |= pack_left_shift_u32(joint1_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint1_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint1_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint1_pos, 24u, 0xffu);

    return (8);
}

int arm_joint1_unpack(
    struct arm_joint1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint1_pos;
    uint32_t joint1_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint1_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint1_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint1_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint1_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint1_vel, &joint1_vel, sizeof(dst_p->joint1_vel));
    joint1_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint1_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint1_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint1_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint1_pos, &joint1_pos, sizeof(dst_p->joint1_pos));

    return (0);
}

int arm_joint1_init(struct arm_joint1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint1_t));

    return 0;
}

float arm_joint1_joint1_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint1_joint1_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint1_joint1_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint1_joint1_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint1_joint1_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint1_joint1_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint1_joint1_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint1_joint1_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
