/**
 * @file arm.c
 *
 * @brief This source file was generated by cantools version 44.1.0 Sun Sep 20 19:32:42 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "arm.h"

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int arm_joint0_pack(
    uint8_t *dst_p,
    const struct arm_joint0_t *src_p,
    size_t size)
{
    uint32_t joint0_pos;
    uint32_t joint0_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint0_vel, &src_p->joint0_vel, sizeof(joint0_vel));
    dst_p[0] |= pack_left_shift_u32(joint0_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint0_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint0_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint0_vel, 24u, 0xffu);
    memcpy(&joint0_pos, &src_p->joint0_pos, sizeof(joint0_pos));
    dst_p[4] |= pack_left_shift_u32(joint0_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint0_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint0_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint0_pos, 24u, 0xffu);

    return (8);
}

int arm_joint0_unpack(
    struct arm_joint0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint0_pos;
    uint32_t joint0_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint0_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint0_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint0_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint0_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint0_vel, &joint0_vel, sizeof(dst_p->joint0_vel));
    joint0_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint0_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint0_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint0_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint0_pos, &joint0_pos, sizeof(dst_p->joint0_pos));

    return (0);
}

int arm_joint0_init(struct arm_joint0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint0_t));

    return 0;
}

float arm_joint0_joint0_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint0_joint0_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint0_joint0_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint0_joint0_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint0_joint0_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint0_joint0_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint0_joint0_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint0_joint0_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int arm_joint1_pack(
    uint8_t *dst_p,
    const struct arm_joint1_t *src_p,
    size_t size)
{
    uint32_t joint1_pos;
    uint32_t joint1_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint1_vel, &src_p->joint1_vel, sizeof(joint1_vel));
    dst_p[0] |= pack_left_shift_u32(joint1_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint1_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint1_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint1_vel, 24u, 0xffu);
    memcpy(&joint1_pos, &src_p->joint1_pos, sizeof(joint1_pos));
    dst_p[4] |= pack_left_shift_u32(joint1_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint1_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint1_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint1_pos, 24u, 0xffu);

    return (8);
}

int arm_joint1_unpack(
    struct arm_joint1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint1_pos;
    uint32_t joint1_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint1_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint1_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint1_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint1_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint1_vel, &joint1_vel, sizeof(dst_p->joint1_vel));
    joint1_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint1_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint1_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint1_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint1_pos, &joint1_pos, sizeof(dst_p->joint1_pos));

    return (0);
}

int arm_joint1_init(struct arm_joint1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint1_t));

    return 0;
}

float arm_joint1_joint1_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint1_joint1_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint1_joint1_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint1_joint1_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint1_joint1_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint1_joint1_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint1_joint1_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint1_joint1_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int arm_joint2_pack(
    uint8_t *dst_p,
    const struct arm_joint2_t *src_p,
    size_t size)
{
    uint32_t joint2_pos;
    uint32_t joint2_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint2_vel, &src_p->joint2_vel, sizeof(joint2_vel));
    dst_p[0] |= pack_left_shift_u32(joint2_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint2_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint2_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint2_vel, 24u, 0xffu);
    memcpy(&joint2_pos, &src_p->joint2_pos, sizeof(joint2_pos));
    dst_p[4] |= pack_left_shift_u32(joint2_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint2_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint2_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint2_pos, 24u, 0xffu);

    return (8);
}

int arm_joint2_unpack(
    struct arm_joint2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint2_pos;
    uint32_t joint2_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint2_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint2_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint2_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint2_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint2_vel, &joint2_vel, sizeof(dst_p->joint2_vel));
    joint2_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint2_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint2_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint2_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint2_pos, &joint2_pos, sizeof(dst_p->joint2_pos));

    return (0);
}

int arm_joint2_init(struct arm_joint2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint2_t));

    return 0;
}

float arm_joint2_joint2_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint2_joint2_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint2_joint2_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint2_joint2_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint2_joint2_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint2_joint2_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint2_joint2_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint2_joint2_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int arm_joint3_pack(
    uint8_t *dst_p,
    const struct arm_joint3_t *src_p,
    size_t size)
{
    uint32_t joint3_pos;
    uint32_t joint3_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint3_vel, &src_p->joint3_vel, sizeof(joint3_vel));
    dst_p[0] |= pack_left_shift_u32(joint3_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint3_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint3_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint3_vel, 24u, 0xffu);
    memcpy(&joint3_pos, &src_p->joint3_pos, sizeof(joint3_pos));
    dst_p[4] |= pack_left_shift_u32(joint3_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint3_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint3_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint3_pos, 24u, 0xffu);

    return (8);
}

int arm_joint3_unpack(
    struct arm_joint3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint3_pos;
    uint32_t joint3_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint3_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint3_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint3_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint3_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint3_vel, &joint3_vel, sizeof(dst_p->joint3_vel));
    joint3_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint3_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint3_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint3_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint3_pos, &joint3_pos, sizeof(dst_p->joint3_pos));

    return (0);
}

int arm_joint3_init(struct arm_joint3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint3_t));

    return 0;
}

float arm_joint3_joint3_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint3_joint3_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint3_joint3_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint3_joint3_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint3_joint3_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint3_joint3_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint3_joint3_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint3_joint3_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int arm_joint4_pack(
    uint8_t *dst_p,
    const struct arm_joint4_t *src_p,
    size_t size)
{
    uint32_t joint4_pos;
    uint32_t joint4_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint4_vel, &src_p->joint4_vel, sizeof(joint4_vel));
    dst_p[0] |= pack_left_shift_u32(joint4_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint4_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint4_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint4_vel, 24u, 0xffu);
    memcpy(&joint4_pos, &src_p->joint4_pos, sizeof(joint4_pos));
    dst_p[4] |= pack_left_shift_u32(joint4_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint4_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint4_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint4_pos, 24u, 0xffu);

    return (8);
}

int arm_joint4_unpack(
    struct arm_joint4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint4_pos;
    uint32_t joint4_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint4_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint4_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint4_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint4_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint4_vel, &joint4_vel, sizeof(dst_p->joint4_vel));
    joint4_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint4_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint4_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint4_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint4_pos, &joint4_pos, sizeof(dst_p->joint4_pos));

    return (0);
}

int arm_joint4_init(struct arm_joint4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint4_t));

    return 0;
}

float arm_joint4_joint4_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint4_joint4_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint4_joint4_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint4_joint4_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint4_joint4_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint4_joint4_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint4_joint4_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint4_joint4_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int arm_joint5_pack(
    uint8_t *dst_p,
    const struct arm_joint5_t *src_p,
    size_t size)
{
    uint32_t joint5_pos;
    uint32_t joint5_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&joint5_vel, &src_p->joint5_vel, sizeof(joint5_vel));
    dst_p[0] |= pack_left_shift_u32(joint5_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(joint5_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(joint5_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(joint5_vel, 24u, 0xffu);
    memcpy(&joint5_pos, &src_p->joint5_pos, sizeof(joint5_pos));
    dst_p[4] |= pack_left_shift_u32(joint5_pos, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(joint5_pos, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(joint5_pos, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(joint5_pos, 24u, 0xffu);

    return (8);
}

int arm_joint5_unpack(
    struct arm_joint5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t joint5_pos;
    uint32_t joint5_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    joint5_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    joint5_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    joint5_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    joint5_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->joint5_vel, &joint5_vel, sizeof(dst_p->joint5_vel));
    joint5_pos = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    joint5_pos |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    joint5_pos |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    joint5_pos |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->joint5_pos, &joint5_pos, sizeof(dst_p->joint5_pos));

    return (0);
}

int arm_joint5_init(struct arm_joint5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct arm_joint5_t));

    return 0;
}

float arm_joint5_joint5_vel_encode(double value)
{
    return (float)(value);
}

double arm_joint5_joint5_vel_decode(float value)
{
    return ((double)value);
}

bool arm_joint5_joint5_vel_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint5_joint5_vel_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float arm_joint5_joint5_pos_encode(double value)
{
    return (float)(value);
}

double arm_joint5_joint5_pos_decode(float value)
{
    return ((double)value);
}

bool arm_joint5_joint5_pos_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool arm_joint5_joint5_pos_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}
