/**
 * @file arm.h
 *
 * @brief This header file was generated by cantools version 44.1.0 Sun Sep 20 19:32:42 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ARM_H
#define ARM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ARM_JOINT0_FRAME_ID (0xc8u)
#define ARM_JOINT1_FRAME_ID (0xc9u)
#define ARM_JOINT2_FRAME_ID (0xcau)
#define ARM_JOINT3_FRAME_ID (0xcbu)
#define ARM_JOINT4_FRAME_ID (0xccu)
#define ARM_JOINT5_FRAME_ID (0xcdu)

/* Frame lengths in bytes. */
#define ARM_JOINT0_LENGTH (8u)
#define ARM_JOINT1_LENGTH (8u)
#define ARM_JOINT2_LENGTH (8u)
#define ARM_JOINT3_LENGTH (8u)
#define ARM_JOINT4_LENGTH (8u)
#define ARM_JOINT5_LENGTH (8u)

/* Extended or standard frame types. */
#define ARM_JOINT0_IS_EXTENDED (0)
#define ARM_JOINT1_IS_EXTENDED (0)
#define ARM_JOINT2_IS_EXTENDED (0)
#define ARM_JOINT3_IS_EXTENDED (0)
#define ARM_JOINT4_IS_EXTENDED (0)
#define ARM_JOINT5_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define ARM_JOINT0_NAME "joint0"
#define ARM_JOINT1_NAME "joint1"
#define ARM_JOINT2_NAME "joint2"
#define ARM_JOINT3_NAME "joint3"
#define ARM_JOINT4_NAME "joint4"
#define ARM_JOINT5_NAME "joint5"

/* Signal Names. */
#define ARM_JOINT0_JOINT0_VEL_NAME "joint0_vel"
#define ARM_JOINT0_JOINT0_POS_NAME "joint0_pos"
#define ARM_JOINT1_JOINT1_VEL_NAME "joint1_vel"
#define ARM_JOINT1_JOINT1_POS_NAME "joint1_pos"
#define ARM_JOINT2_JOINT2_VEL_NAME "joint2_vel"
#define ARM_JOINT2_JOINT2_POS_NAME "joint2_pos"
#define ARM_JOINT3_JOINT3_VEL_NAME "joint3_vel"
#define ARM_JOINT3_JOINT3_POS_NAME "joint3_pos"
#define ARM_JOINT4_JOINT4_VEL_NAME "joint4_vel"
#define ARM_JOINT4_JOINT4_POS_NAME "joint4_pos"
#define ARM_JOINT5_JOINT5_VEL_NAME "joint5_vel"
#define ARM_JOINT5_JOINT5_POS_NAME "joint5_pos"

/**
 * Signals in message joint0.
 *
 * All signal values are as on the CAN bus.
 */
struct arm_joint0_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint0_vel;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint0_pos;
};

/**
 * Signals in message joint1.
 *
 * All signal values are as on the CAN bus.
 */
struct arm_joint1_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint1_vel;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint1_pos;
};

/**
 * Signals in message joint2.
 *
 * All signal values are as on the CAN bus.
 */
struct arm_joint2_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint2_vel;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint2_pos;
};

/**
 * Signals in message joint3.
 *
 * All signal values are as on the CAN bus.
 */
struct arm_joint3_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint3_vel;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint3_pos;
};

/**
 * Signals in message joint4.
 *
 * All signal values are as on the CAN bus.
 */
struct arm_joint4_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint4_vel;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint4_pos;
};

/**
 * Signals in message joint5.
 *
 * All signal values are as on the CAN bus.
 */
struct arm_joint5_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint5_vel;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float joint5_pos;
};

/**
 * Pack message joint0.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int arm_joint0_pack(
    uint8_t *dst_p,
    const struct arm_joint0_t *src_p,
    size_t size);

/**
 * Unpack message joint0.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int arm_joint0_unpack(
    struct arm_joint0_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from joint0.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int arm_joint0_init(struct arm_joint0_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint0_joint0_vel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint0_joint0_vel_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint0_joint0_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint0_joint0_vel_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint0_joint0_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint0_joint0_pos_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint0_joint0_pos_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint0_joint0_pos_is_in_phys_range(double value);

/**
 * Pack message joint1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int arm_joint1_pack(
    uint8_t *dst_p,
    const struct arm_joint1_t *src_p,
    size_t size);

/**
 * Unpack message joint1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int arm_joint1_unpack(
    struct arm_joint1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from joint1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int arm_joint1_init(struct arm_joint1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint1_joint1_vel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint1_joint1_vel_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint1_joint1_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint1_joint1_vel_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint1_joint1_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint1_joint1_pos_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint1_joint1_pos_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint1_joint1_pos_is_in_phys_range(double value);

/**
 * Pack message joint2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int arm_joint2_pack(
    uint8_t *dst_p,
    const struct arm_joint2_t *src_p,
    size_t size);

/**
 * Unpack message joint2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int arm_joint2_unpack(
    struct arm_joint2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from joint2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int arm_joint2_init(struct arm_joint2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint2_joint2_vel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint2_joint2_vel_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint2_joint2_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint2_joint2_vel_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint2_joint2_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint2_joint2_pos_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint2_joint2_pos_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint2_joint2_pos_is_in_phys_range(double value);

/**
 * Pack message joint3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int arm_joint3_pack(
    uint8_t *dst_p,
    const struct arm_joint3_t *src_p,
    size_t size);

/**
 * Unpack message joint3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int arm_joint3_unpack(
    struct arm_joint3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from joint3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int arm_joint3_init(struct arm_joint3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint3_joint3_vel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint3_joint3_vel_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint3_joint3_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint3_joint3_vel_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint3_joint3_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint3_joint3_pos_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint3_joint3_pos_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint3_joint3_pos_is_in_phys_range(double value);

/**
 * Pack message joint4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int arm_joint4_pack(
    uint8_t *dst_p,
    const struct arm_joint4_t *src_p,
    size_t size);

/**
 * Unpack message joint4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int arm_joint4_unpack(
    struct arm_joint4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from joint4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int arm_joint4_init(struct arm_joint4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint4_joint4_vel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint4_joint4_vel_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint4_joint4_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint4_joint4_vel_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint4_joint4_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint4_joint4_pos_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint4_joint4_pos_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint4_joint4_pos_is_in_phys_range(double value);

/**
 * Pack message joint5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int arm_joint5_pack(
    uint8_t *dst_p,
    const struct arm_joint5_t *src_p,
    size_t size);

/**
 * Unpack message joint5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int arm_joint5_unpack(
    struct arm_joint5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from joint5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int arm_joint5_init(struct arm_joint5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint5_joint5_vel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint5_joint5_vel_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint5_joint5_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint5_joint5_vel_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float arm_joint5_joint5_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double arm_joint5_joint5_pos_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint5_joint5_pos_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool arm_joint5_joint5_pos_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
